Workspace
miloszizic/kanbak pull request #1
Opened 2021-04-29 09:57 UTC by miloszizic

Custom to official module migration.
Added workspaces.

2021-04-29 12:51 UTC, vladimirmukhin requested changes

2021-04-29 12:51 UTC, vladimirmukhin commented on output.tf
> +}
It's a good practice not to expose outputs unless it's really required. Consumed by another terraform state, for example

2021-04-29 12:51 UTC, vladimirmukhin commented on workspace/dev/vpc.tfvars
> +availability_zones = ["us-east-1a", "us-east-1b"]
It's better to replace hardcoded availability zones with this:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones

2021-04-29 12:51 UTC, vladimirmukhin commented on main.tf
> +  azs = var.availability_zones
When multiple arguments with single-line values appear on consecutive lines at the same nesting level, align their equals signs.

There is no need to do this manually, just run `terraform fmt -recursive` in the root of the project and commit changes

2021-04-29 12:51 UTC, vladimirmukhin commented on main.tf
> +	  cidr_blocks = "0.0.0.0/0"
It's better not to open SSH to the entire internet. Use your public IP instead

2021-04-29 12:51 UTC, vladimirmukhin commented on main.tf
> +  cluster_name = "kanbak-eks"
This variable should be workspaced

2021-04-29 12:51 UTC, vladimirmukhin commented on main.tf
> +  name                   = "Bastion"
This variable should be workspaced

2021-04-30 17:57 UTC, miloszizic commented on output.tf
> +}
Fixed

2021-04-30 17:57 UTC, miloszizic commented on workspace/dev/vpc.tfvars
> +availability_zones = ["us-east-1a", "us-east-1b"]
Fixed

2021-04-30 17:57 UTC, miloszizic commented on main.tf
> +  azs = var.availability_zones
Fixed

2021-04-30 17:57 UTC, miloszizic commented on main.tf
> +	  cidr_blocks = "0.0.0.0/0"
Fixed

2021-04-30 17:57 UTC, miloszizic commented on main.tf
> +  cluster_name = "kanbak-eks"
Fixed

2021-04-30 17:57 UTC, miloszizic commented on main.tf
> +  name                   = "Bastion"
Fixed

2021-04-30 17:58 UTC, merged